<div class="staff-blurb-title">
    Staff Mini-Bio: Justin
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    Until last year, I lived my entire life in various parts of the Bay Area (California).
    I spent 12 years at UC Berkeley getting all my degrees (BS, MS, PhD).
    Now a CSE Lecturer at UW!  =)<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - ultimate frisbee, board games, hiking, camping, singing (a cappella)<br>
    - I am decently dexterous with my left hand.<br>
    - I can solve a few variants of the Rubik's Cube (I am NOT a speedcuber).<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - So I have this story that involves kayaking, sea lions, a long night on a rock beach, a helicopter, and the coast guard... =P<br>
    - I once ran a marathon. It was hard.<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - Teaching CSE351<br>
    - Course development for CSE120 and CSE333<br>
    - DiscNW Fall Team League (ultimate)
</div>
