<div class="staff-blurb-title">
    Staff Mini-Bio: Kevin
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    I was born in Daegu, South Korea but grew up in Bellevue, WA. I was introduced to CS in middle
    school in a Robotics club. I really enjoyed building scripts in the robotics club and other
    clubs I joined in high school, so I decided to study CS at UW.
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    Tennis! Saxophonist/Clarinetist.
    <br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    I got to travel to China with the UW Wind Ensemble my freshman year. I played with the ensemble
    in front of hundreds of Chinese citizens and got to eat a lot of good food :)
    <br><br>

    <b>HOW MUCH PROGRAMMING HAVE YOU DONE (AND WHAT LANGUAGES)?</b><br>
    I first learn to program the LEGO NXT robot in a robotics club in middle school. Since then, I
    learned to program in Python, Java, C, C++, and JavaScript.
    <br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR TIME THIS QUARTER?</b><br>
    Making an autonomous toy race car, creating a cool Virtual Reality app, doing some Distributed
    Systems things, TAing 180, and Tennis.
</div>
