<div class="staff-blurb-title">
    Staff Mini-Bio: Ryan
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    I grew up in California before moving to Seattle for college at the UW. In undergrad I studied
    Physics and Astronomy, and went to UC Berkeley as an Astrophysics Ph.D. student. Wanting to do
    more programming, I wound up working in industry before starting grad school at UW for computer
    science. I'm now a part-time lecturer at the Paul Allen School for CSE!
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    My hobbies are rock climbing and some very unskilled photography and painting.
    <br><br>

    <b>HOW MUCH PROGRAMMING HAVE YOU DONE (AND WHAT LANGUAGES)?</b><br>
    I've programmed in a variety of languages over the years. Most recently I work in Java and
    Python, but I started out programming in C and Fortran when I was doing Astrophysics research on
    numerical simulation software.
    <br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR TIME THIS QUARTER?</b><br>
    Since this is the first time CSE is offering the 180 course, I'm spending most of my time
    working on that class!
</div>
