<div class="staff-blurb-title">
    Staff Mini-Bio: Michael
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    - I was born and raised in Lexington, MA(just outside of Boston).<br>
    - I am a second year at UW studying Math and CS.<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - I enjoy hiking, yoga, and reading.<br>
    - Beyond that I like to run and bike when I have the time.<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - I got to be a part of a startup through their stay at Y Combinator and for a few months afterward.<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - Projects<br>
    - Work(Both TA and some light contracting CS work)<br>
    - Math<br><br>
</div>
