<div class="staff-blurb-title">
    Staff Mini-Bio: Andrew
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    Taiwan, then Bellevue, then Lynnwood, then Seattle. I did Running Start in high school and got
    an Associates in Mechanical Engineering and Computer Engineering at Edmonds Community College.
    This is my second year at UW and I'm a Computer Engineering major doing 5th year masters next
    year.
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    Sleeping, watching shows, listening to music, hanging with friends, and going to different
    places to eat.
    <br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    Not particularly? It depends on your definition of remarkable memorable. I remember waking up
    this morning and feeling pretty dead.
    <br><br>

    <b>HOW MUCH PROGRAMMING HAVE YOU DONE (AND WHAT LANGUAGES)?</b><br>
    Some programming, mostly just for classes. Visual Basic, Java, TI Basic, C, C++, SystemVerilog,
    Verilog, Python, some JavaScript, HTML.
    <br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR TIME THIS QUARTER?</b><br>
    Mostly classes: Distributed Systems, Computer Architecture II, VR Capstone, Graphics, and TAing
    this class. I also need to find something to do for the summer.
</div>
