<div class="staff-blurb-title">
    Staff Mini-Bio: Parker
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    - I was born and went through school 90 miles north of UW in Bellingham, WA.
    - I went to public schools, going to Squalicum High School and doing part-time 
      Running Start at Whatcom Community College
    - I began UW after graduating High School in 2015.<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - I can play the drums, both jazz and marching.
    - Marathon Sunday afternoon naps.
    - I enjoy playing around with Arduino projects and blinking lights.<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - I was in the Husky Drumline my freshman year, which was a really cool experience.
    - I cannot recommend the hiking around Mt. Baker enough!<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - Context switching between student mode and TA mode.
    - 3 CSE classes
    - This is my first time TA'ing, so I am sure learning how to be a good TA will
      keep me very busy.
    - I am going to India over winter break, so preparations for that journey.<br><br>
</div>
