<div class="staff-blurb-title">
    Staff Mini-Bio: Ryan
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    I was born in Milwaukee, Wisconsin, but have lived in Tacoma, Washington for most of my life. I
    came into college planning to do medical school, but I took CSE 142 my first quarter at UW and
    ended up dropping medicine after getting into CSE.
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    Guitar, ukulele, singing, dancing, Netflix, the occasional video game, Sudoku, and I'm a huge
    sucker for word games (e.g. crossword puzzles, scrabble, etc.)
    <br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    If you ask me, no. If you ask my friends, maybe. I did go to Disneyland over spring break and,
    for me, that was memorable.
    <br><br>

    <b>HOW MUCH PROGRAMMING HAVE YOU DONE (AND WHAT LANGUAGES)?</b><br>
    About 3.5 years of programming on various scales in Java, Python, C#, and React, though I only
    really claim to know Java.
    <br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR TIME THIS QUARTER?</b><br>
    TAing for this class, some part-time work, FASA sa UW (I'm an officer!), and, like many of us,
    figuring out what to do with my life.
</div>
