<div class="staff-blurb-title">
    Staff Mini-Bio: Ryan
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    - I have lived in the Bay Area for 18 years before coming up to Seattle. I am
 currently a junior in CS, and I basically decided on CS related majors in high school.<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - I used to play chess a lot, but now just occasionally.<br>
    - I like to sing in choirs and by myself.<br>
    - Does being diamond in League count as a skill?<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - Solar Eclipse hur dur.<br>
    - I have performed in various churches in Spain and Portugal.<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - TAing CSE 351<br>
    - Choir<br>
    - Hong Kong Student Associations<br>
    - Looking for internships(rip)<br><br>
</div>
