<div class="staff-blurb-title">
    Staff Mini-Bio: Savanna
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    - I grew up in the Redmond/Bellevue area of Washington.  I was homeschooled from kindergarten to 12th grade.  Now I am in my third year at UW, in the Interdisciplinary Honors Program, and studying both Computer Science and Informatics.<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - Any type of puzzle solving<br><br>
	-Making art out of whatever I can find:3D printing, laser cutting, hand lettering, drawing, painting, crafting, Arduino projects, etc.<br><br>
	-Writing poetry<br><br>
	-Biking<br><br>
	-Swing dancing<br><br>
	-Singing (jazz, choral, a cappella)<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - I became a multi-cellular organism.  I woke up this morning.  I am conscious and self-aware.<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - Besides being a TA, I will be a peer advisor for Informatics, an Informatics iSquad leader, and the webmaster for UW Swing Kids.  I will also bike as often as possible and leave time for family, friends, and pursuing spontaneous activities.  I will also be turning 20 :/<br><br>
</div>
