<div class="staff-blurb-title">
    Staff Mini-Bio: Sam 
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    I grew up in Studio City (a suburb of Los Angeles).Before coming to UW, I learned a bit about CS through online tutorials and an iPhone development class.
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    Recently, I've been trying to become a better cook. I've found good recipes on the NYTimes recipe page. My best dish is my carbonara.
    <br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    Last summer I traveled to Japan, where I had some great ramen and got to ride the Shinkansen high speed train.
    <br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR TIME THIS QUARTER?</b><br>
    TAing for this course, classes, and research.
</div>
