<div class="staff-blurb-title">
    Staff Mini-Bio: Trevor
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    Grew up in Virginia. Undergrad at UVA, did 4 years in the Peace Corps, started a PhD at UW in
    2012.
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    I like to juggle and unicycle (sometimes at the same time).
    <br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    Spent 6mo teaching math and science in rural Liberia (in Gblonlay Liberia).
    <br><br>

    <b>HOW MUCH PROGRAMMING HAVE YOU DONE (AND WHAT LANGUAGES)?</b><br>
    Live and breath Python and Linux.
    <br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR TIME THIS QUARTER?</b><br>
    I'm graduating so finishing my thesis.
</div>
