<div class="staff-blurb-title">
    Staff Mini-Bio: Vinny
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    - I have lived in the greater Seattle area my entire life<br>
    - I attended Issaquah High School and am currently an undergrad (2<sup>nd</sup> year) studying Computer Science and UW (which I have been planning to do for as long as I remember)<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - I enjoy playing ultimate frisbee, football and basketball (casually), and video games<br>
    - I stream games and make YouTube videos (my channel is VPAL55 on Twitch and YouTube for anyone that is curious *wink wink*)<br>
    - I have been playing the piano and doing martial arts since I was 5 (less so recently with school)<br>
    - Outside of CS I'm very interested in biochemistry, neuroscience, biophysics, and political science<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - Nope, I lead a relatively boring life mostly focusing on school and work<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - Being a TA for CSE 351 (obviously)<br>
    - My classes will take up a lot of time, especially CSE 451<br>
    - Smash club (where we play the video game: Super Smash Bros)<br>
    - Hobbies<br><br>
</div>
