<div class="staff-blurb-title">
    Staff Mini-Bio: Sam Wolfson
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    I grew up right here in Seattle! I've always loved taking things apart, trying to fix them when they inevitably break, and figuring out how they work in the process. This path of problem-solving eventually led me to computers, and that led me to UW.
    
    <br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    In my free time I enjoy skiing, playing guitar, and camping. I can make a pretty good apple pie.<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    I went to Madras, Oregon this summer and watched the eclipse in totality!<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    Husky Running Club (<a href="http://dawgs.run" target="_blank">join us, we're friendly!</a>), TAing for this class, and keeping up with my own courses!
    
    <br><br>
</div>
