<div class="staff-blurb-title">
    Staff Mini-Bio: Lucas
</div>
<div class="staff-blurb-content">
    <b>WHERE DID YOU GROW UP? WHAT WAS YOUR ACADEMIC PATH?</b><br>
    - I'm from Battle Ground Washington (near Portland Oregon)<br>
    - I attended Battle Ground High School, and then did the <a href="http://www.k12.wa.us/SecondaryEducation/CareerCollegeReadiness/RunningStart.aspx">Running Start</a> program at Clark College<br><br>

    <b>WHAT ARE SOME OF YOUR HOBBIES, TALENTS, AND SKILLS?</b><br>
    - My hobbies include playing basketball, coding and teaching :)<br>
    - I grew up riding trails on dirtbikes and have been coding for 2 years now, so I'm relatively good at those activities<br><br>

    <b>HAVE YOU DONE OR EXPERIENCED ANYTHING REMARKABLE OR MEMORABLE?</b><br>
    - Nothing comes to mind honestly<br><br>

    <b>WHAT COMMITMENTS WILL BE CONSUMING YOUR CYCLES THIS QUARTER?</b><br>
    - Classes (Networks and AI)<br>
    - Side projects (probably working together on stuff with my roommate)<br>
    - Working out (and playing basketball afterwards on the IMA courts)<br>
    - TA'ing :)<br><br>
</div>

